name: Validate test_data.sh scripts

on:
  pull_request:
    paths:
      - '**/test_data.sh'

jobs:
  validate-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate test_data.sh scripts
        id: validate
        run: |
          # Find all test_data.sh files in the PR changes
          files=$(git diff --name-only HEAD^ -- '**/test_data.sh')
          
          if [ -z "$files" ]; then
            echo "No test_data.sh files modified"
            exit 0
          fi

          has_errors=false
          error_message=""

          for file in $files; do
            echo "Checking $file"
            
            # Get the first non-comment, non-empty, non-whitespace command in the script
            first_cmd=$(awk '
              /^[[:space:]]*#/ { next }  # Skip comment lines
              /^[[:space:]]*$/ { next }   # Skip empty lines
              {
                # Print the first word and exit
                print $1
                exit
              }
            ' "$file")
            
            if [ "$first_cmd" != "cp" ]; then
              has_errors=true
              error_message+="❌ Error in $file: First command must be 'cp', but found '${first_cmd:-none}'\n"
              error_message+="First line with command: $(grep -v -E '^[[:space:]]*(#|$)' "$file" | head -n 1)\n\n"
            else
              echo "✅ $file starts with 'cp'"
            fi
          done

          if $has_errors; then
            echo "::error::Some test_data.sh files don't start with 'cp' command"
            echo -e "$error_message"
            exit 1
          else
            echo "All test_data.sh files are valid"
          fi
